version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/NewsEmotionsExtraction
permissions:
  - object: /home/ubuntu/NewsEmotionsExtraction
    mode: 755
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
   - location: /home/ubuntu/NewsEmotionsExtraction/install_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: /home/ubuntu/NewsEmotionsExtraction/start_server.sh
     timeout: 300
     runas: root